// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRoom = "rooms"

// Room mapped from table <rooms>
type Room struct {
	RoomID   int32  `gorm:"column:room_id;primaryKey;autoIncrement:true" json:"room_id"`
	RoomName string `gorm:"column:room_name;not null" json:"room_name"`
}

// TableName Room's table name
func (*Room) TableName() string {
	return TableNameRoom
}
